/*
    Copyright 2008 Bilal Khan
    grouptheory@gmail.com

    This file is part of MKSolver.

    MKSolver is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MKSolver is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
*/

package report;

import ge.GE;
import ge.GEFactory;
import ge.Latex;
import ge.CancellationDiagramAnalysis_GEDecorator;
import equation.GroupWord;
import equation.QuadraticSystem;
import cancellation.Diagram;
import cancellation.DiagramTreeNode;
import cancellation.ICancellationDiagramAnalysis;
import cancellation.CancellationDiagramFactory;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;

/**
 *
 * @author grouptheory
 */
public class CancellationDiagramReport extends AbstractReport {
    
    private static String SUFFIX = "-CancellationDiagrams.tex";

    String latexHeader() {
        String s = "";
        s+="\\documentclass[final]{article}\n";
        s+="\\usepackage{amssymb,amsmath,amsfonts}\n";
        s+="\\usepackage[dvips]{graphicx}\n";
        s+="\\usepackage{longtable}\n";
        s+="\\usepackage{pstricks-add,pst-slpe}\n";
        s+="\\begin{document}\n";
        if ( ! params.MKParams.FLAG_REPORT_DATE) {
            s+="\\date{}\n";
        }
        return s;
    }

    String latexTitle(GroupWord eq) {
        String s="";
        s+="\\title{\n";
        s+="  {\\Large The Cancellation Diagrams of \\\\";
        s += "$";
        s += equation.LatexAdapter.instance().renderGroupEquation(eq);
        s += "$";
        s += "\\\\ in a Free Group}\n";
        s+="  {\\normalsize\n";
        s+="   \\author{Bilal Khan\n";
        s+="        \\thanks{Department of Mathematics and Computer Science, John Jay College of Criminal Justice, City University of New York (CUNY).}\n";
        s+="   \\and M-K Solver\n";
        s+="        \\thanks{This report was generated automatically by software developed with support from the National Security Agency Grant H98230-06-1-0042.}\n";
        s+="           }\n";
        s+="  }\n";
        s+="}\n\n";
        s+="\\maketitle\n\n";
        s+="\n\n\n\n";
        s+="The purpose of this report is to demonstrate the logging facilities of the MKSolver.  ";
        s+="In particular, here we see that the MKSolver is able to accurately enumerate ";
        s+="distinct cancellation diagrams corresponding to an equation over a free group.";
        s+="In this manner, the problem of solving equations in free groups, reduces to ";
        s+="finding a solution in the free {\\em semigroup} of one of finitely many systems ";
        s+="of constraints.  This idea dates back to Makanin (1977) in his discussion of ";
        s+="``partition tables''.";
        return s;
    }

    String latexFooter() {
        String s = "";
        s+="\\section{Acknowledgements}\n";
        s+="The authors acknowledge that this report was generated by software developed as part of a funded project supported by a research grant (H98230-06-1-0042) from the National Security Agency.";
        s+="  We also give special thanks to Alexei Miasnikov and Olga Kharlampovich for many helpful discussions along the way.  ";
        s+="\\end{document}\n";
        return s;
    }

    private GroupWord _eq;

    CancellationDiagramReport(String name, GroupWord eq) {
        super(name+SUFFIX);
        _eq = eq.duplicate();
    }

    public void create() {
        GroupWord prob = _eq.duplicate();
        
        ICancellationDiagramAnalysis analysis;
        // analysis = CancellationDiagramFactory.instance().newDiagramTree(prob);
        analysis = CancellationDiagramFactory.instance().newDiagramProbe(prob);

        analysis.addDecorator(new CancellationDiagramAnalysis_GEDecorator());
        
        writeEntry(latexHeader());
        writeEntry(latexTitle(prob));
        
        cancellation.LatexAdapter.instance().renderCancellationDiagramAnalysis(this, analysis);

        writeEntry(latexFooter());
    }
}
